package com.resources;

import com.html.core.styles.*;
import com.html.core.tag.Element;
import com.html.core.tag.Head;
import com.html.core.tag.intfs.Parent;
import com.html.core.tag.intfs.Visual;
import com.html.core.tag.semantic.Div;
import com.html.core.tag.semantic.Span;
import com.html.core.tag.table.Table;
import com.html.core.tag.table.Td;
import com.html.core.tag.table.Tr;
import com.resources.core.html.ImgFile;
import com.resources.core.html.ResourceFile;
import com.servlet.controller.Page;
import com.servlet.interfaces.Arg;
import com.servlet.interfaces.Endpoint;
import com.servlet.requests.HttpRequest;
import com.utils.Url;
import java.lang.reflect.Field;
import java.lang.reflect.Modifier;

/**
 * @author Miłosz Ziernik
 * @date 20 listopada 2015
 * @encoding UTF-8
 */
public class BsIcon extends ImgFile {

    public final static BsIcon asterisk = new BsIcon("asterisk", "\\2a");
    public final static BsIcon plus = new BsIcon("plus", "\\2b");
    public final static BsIcon euro = new BsIcon("euro", "\\20ac");
    public final static BsIcon minus = new BsIcon("minus", "\\2212");
    public final static BsIcon cloud = new BsIcon("cloud", "\\2601");
    public final static BsIcon envelope = new BsIcon("envelope", "\\2709");
    public final static BsIcon pencil = new BsIcon("pencil", "\\270f");
    public final static BsIcon glass = new BsIcon("glass", "\\e001");
    public final static BsIcon music = new BsIcon("music", "\\e002");
    public final static BsIcon search = new BsIcon("search", "\\e003");
    public final static BsIcon heart = new BsIcon("heart", "\\e005");
    public final static BsIcon star = new BsIcon("star", "\\e006");
    public final static BsIcon starEmpty = new BsIcon("star-empty", "\\e007");
    public final static BsIcon user = new BsIcon("user", "\\e008");
    public final static BsIcon film = new BsIcon("film", "\\e009");
    public final static BsIcon thLarge = new BsIcon("th-large", "\\e010");
    public final static BsIcon th = new BsIcon("th", "\\e011");
    public final static BsIcon thList = new BsIcon("th-list", "\\e012");
    public final static BsIcon ok = new BsIcon("ok", "\\e013");
    public final static BsIcon remove = new BsIcon("remove", "\\e014");
    public final static BsIcon zoomIn = new BsIcon("zoom-in", "\\e015");
    public final static BsIcon zoomOut = new BsIcon("zoom-out", "\\e016");
    public final static BsIcon off = new BsIcon("off", "\\e017");
    public final static BsIcon signal = new BsIcon("signal", "\\e018");
    public final static BsIcon cog = new BsIcon("cog", "\\e019");
    public final static BsIcon trash = new BsIcon("trash", "\\e020");
    public final static BsIcon home = new BsIcon("home", "\\e021");
    public final static BsIcon file = new BsIcon("file", "\\e022");
    public final static BsIcon time = new BsIcon("time", "\\e023");
    public final static BsIcon road = new BsIcon("road", "\\e024");
    public final static BsIcon downloadAlt = new BsIcon("download-alt", "\\e025");
    public final static BsIcon download = new BsIcon("download", "\\e026");
    public final static BsIcon upload = new BsIcon("upload", "\\e027");
    public final static BsIcon inbox = new BsIcon("inbox", "\\e028");
    public final static BsIcon playCircle = new BsIcon("play-circle", "\\e029");
    public final static BsIcon repeat = new BsIcon("repeat", "\\e030");
    public final static BsIcon refresh = new BsIcon("refresh", "\\e031");
    public final static BsIcon listAlt = new BsIcon("list-alt", "\\e032");
    public final static BsIcon lock = new BsIcon("lock", "\\e033");
    public final static BsIcon flag = new BsIcon("flag", "\\e034");
    public final static BsIcon headphones = new BsIcon("headphones", "\\e035");
    public final static BsIcon volumeOff = new BsIcon("volume-off", "\\e036");
    public final static BsIcon volumeDown = new BsIcon("volume-down", "\\e037");
    public final static BsIcon volumeUp = new BsIcon("volume-up", "\\e038");
    public final static BsIcon qrcode = new BsIcon("qrcode", "\\e039");
    public final static BsIcon barcode = new BsIcon("barcode", "\\e040");
    public final static BsIcon tag = new BsIcon("tag", "\\e041");
    public final static BsIcon tags = new BsIcon("tags", "\\e042");
    public final static BsIcon book = new BsIcon("book", "\\e043");
    public final static BsIcon bookmark = new BsIcon("bookmark", "\\e044");
    public final static BsIcon print = new BsIcon("print", "\\e045");
    public final static BsIcon camera = new BsIcon("camera", "\\e046");
    public final static BsIcon font = new BsIcon("font", "\\e047");
    public final static BsIcon bold = new BsIcon("bold", "\\e048");
    public final static BsIcon italic = new BsIcon("italic", "\\e049");
    public final static BsIcon textHeight = new BsIcon("text-height", "\\e050");
    public final static BsIcon textWidth = new BsIcon("text-width", "\\e051");
    public final static BsIcon alignLeft = new BsIcon("align-left", "\\e052");
    public final static BsIcon alignCenter = new BsIcon("align-center", "\\e053");
    public final static BsIcon alignRight = new BsIcon("align-right", "\\e054");
    public final static BsIcon alignJustify = new BsIcon("align-justify", "\\e055");
    public final static BsIcon list = new BsIcon("list", "\\e056");
    public final static BsIcon indentLeft = new BsIcon("indent-left", "\\e057");
    public final static BsIcon indentRight = new BsIcon("indent-right", "\\e058");
    public final static BsIcon facetimeVideo = new BsIcon("facetime-video", "\\e059");
    public final static BsIcon picture = new BsIcon("picture", "\\e060");
    public final static BsIcon mapMarker = new BsIcon("map-marker", "\\e062");
    public final static BsIcon adjust = new BsIcon("adjust", "\\e063");
    public final static BsIcon tint = new BsIcon("tint", "\\e064");
    public final static BsIcon edit = new BsIcon("edit", "\\e065");
    public final static BsIcon share = new BsIcon("share", "\\e066");
    public final static BsIcon check = new BsIcon("check", "\\e067");
    public final static BsIcon move = new BsIcon("move", "\\e068");
    public final static BsIcon stepBackward = new BsIcon("step-backward", "\\e069");
    public final static BsIcon fastBackward = new BsIcon("fast-backward", "\\e070");
    public final static BsIcon backward = new BsIcon("backward", "\\e071");
    public final static BsIcon play = new BsIcon("play", "\\e072");
    public final static BsIcon pause = new BsIcon("pause", "\\e073");
    public final static BsIcon stop = new BsIcon("stop", "\\e074");
    public final static BsIcon forward = new BsIcon("forward", "\\e075");
    public final static BsIcon fastForward = new BsIcon("fast-forward", "\\e076");
    public final static BsIcon stepForward = new BsIcon("step-forward", "\\e077");
    public final static BsIcon eject = new BsIcon("eject", "\\e078");
    public final static BsIcon chevronLeft = new BsIcon("chevron-left", "\\e079");
    public final static BsIcon chevronRight = new BsIcon("chevron-right", "\\e080");
    public final static BsIcon plusSign = new BsIcon("plus-sign", "\\e081");
    public final static BsIcon minusSign = new BsIcon("minus-sign", "\\e082");
    public final static BsIcon removeSign = new BsIcon("remove-sign", "\\e083");
    public final static BsIcon okSign = new BsIcon("ok-sign", "\\e084");
    public final static BsIcon questionSign = new BsIcon("question-sign", "\\e085");
    public final static BsIcon infoSign = new BsIcon("info-sign", "\\e086");
    public final static BsIcon screenshot = new BsIcon("screenshot", "\\e087");
    public final static BsIcon removeCircle = new BsIcon("remove-circle", "\\e088");
    public final static BsIcon okCircle = new BsIcon("ok-circle", "\\e089");
    public final static BsIcon banCircle = new BsIcon("ban-circle", "\\e090");
    public final static BsIcon arrowLeft = new BsIcon("arrow-left", "\\e091");
    public final static BsIcon arrowRight = new BsIcon("arrow-right", "\\e092");
    public final static BsIcon arrowUp = new BsIcon("arrow-up", "\\e093");
    public final static BsIcon arrowDown = new BsIcon("arrow-down", "\\e094");
    public final static BsIcon shareAlt = new BsIcon("share-alt", "\\e095");
    public final static BsIcon resizeFull = new BsIcon("resize-full", "\\e096");
    public final static BsIcon resizeSmall = new BsIcon("resize-small", "\\e097");
    public final static BsIcon exclamationSign = new BsIcon("exclamation-sign", "\\e101");
    public final static BsIcon gift = new BsIcon("gift", "\\e102");
    public final static BsIcon leaf = new BsIcon("leaf", "\\e103");
    public final static BsIcon fire = new BsIcon("fire", "\\e104");
    public final static BsIcon eyeOpen = new BsIcon("eye-open", "\\e105");
    public final static BsIcon eyeClose = new BsIcon("eye-close", "\\e106");
    public final static BsIcon warningSign = new BsIcon("warning-sign", "\\e107");
    public final static BsIcon plane = new BsIcon("plane", "\\e108");
    public final static BsIcon calendar = new BsIcon("calendar", "\\e109");
    public final static BsIcon random = new BsIcon("random", "\\e110");
    public final static BsIcon comment = new BsIcon("comment", "\\e111");
    public final static BsIcon magnet = new BsIcon("magnet", "\\e112");
    public final static BsIcon chevronUp = new BsIcon("chevron-up", "\\e113");
    public final static BsIcon chevronDown = new BsIcon("chevron-down", "\\e114");
    public final static BsIcon retweet = new BsIcon("retweet", "\\e115");
    public final static BsIcon shoppingCart = new BsIcon("shopping-cart", "\\e116");
    public final static BsIcon folderClose = new BsIcon("folder-close", "\\e117");
    public final static BsIcon folderOpen = new BsIcon("folder-open", "\\e118");
    public final static BsIcon resizeVertical = new BsIcon("resize-vertical", "\\e119");
    public final static BsIcon resizeHorizontal = new BsIcon("resize-horizontal", "\\e120");
    public final static BsIcon hdd = new BsIcon("hdd", "\\e121");
    public final static BsIcon bullhorn = new BsIcon("bullhorn", "\\e122");
    public final static BsIcon bell = new BsIcon("bell", "\\e123");
    public final static BsIcon certificate = new BsIcon("certificate", "\\e124");
    public final static BsIcon thumbsUp = new BsIcon("thumbs-up", "\\e125");
    public final static BsIcon thumbsDown = new BsIcon("thumbs-down", "\\e126");
    public final static BsIcon handRight = new BsIcon("hand-right", "\\e127");
    public final static BsIcon handLeft = new BsIcon("hand-left", "\\e128");
    public final static BsIcon handUp = new BsIcon("hand-up", "\\e129");
    public final static BsIcon handDown = new BsIcon("hand-down", "\\e130");
    public final static BsIcon circleArrowRight = new BsIcon("circle-arrow-right", "\\e131");
    public final static BsIcon circleArrowLeft = new BsIcon("circle-arrow-left", "\\e132");
    public final static BsIcon circleArrowUp = new BsIcon("circle-arrow-up", "\\e133");
    public final static BsIcon circleArrowDown = new BsIcon("circle-arrow-down", "\\e134");
    public final static BsIcon globe = new BsIcon("globe", "\\e135");
    public final static BsIcon wrench = new BsIcon("wrench", "\\e136");
    public final static BsIcon tasks = new BsIcon("tasks", "\\e137");
    public final static BsIcon filter = new BsIcon("filter", "\\e138");
    public final static BsIcon briefcase = new BsIcon("briefcase", "\\e139");
    public final static BsIcon fullscreen = new BsIcon("fullscreen", "\\e140");
    public final static BsIcon dashboard = new BsIcon("dashboard", "\\e141");
    public final static BsIcon paperclip = new BsIcon("paperclip", "\\e142");
    public final static BsIcon heartEmpty = new BsIcon("heart-empty", "\\e143");
    public final static BsIcon link = new BsIcon("link", "\\e144");
    public final static BsIcon phone = new BsIcon("phone", "\\e145");
    public final static BsIcon pushpin = new BsIcon("pushpin", "\\e146");
    public final static BsIcon usd = new BsIcon("usd", "\\e148");
    public final static BsIcon gbp = new BsIcon("gbp", "\\e149");
    public final static BsIcon sort = new BsIcon("sort", "\\e150");
    public final static BsIcon sortByAlphabet = new BsIcon("sort-by-alphabet", "\\e151");
    public final static BsIcon sortByAlphabetAlt = new BsIcon("sort-by-alphabet-alt", "\\e152");
    public final static BsIcon sortByOrder = new BsIcon("sort-by-order", "\\e153");
    public final static BsIcon sortByOrderAlt = new BsIcon("sort-by-order-alt", "\\e154");
    public final static BsIcon sortByAttributes = new BsIcon("sort-by-attributes", "\\e155");
    public final static BsIcon sortByAttributesAlt = new BsIcon("sort-by-attributes-alt", "\\e156");
    public final static BsIcon unchecked = new BsIcon("unchecked", "\\e157");
    public final static BsIcon expand = new BsIcon("expand", "\\e158");
    public final static BsIcon collapseDown = new BsIcon("collapse-down", "\\e159");
    public final static BsIcon collapseUp = new BsIcon("collapse-up", "\\e160");
    public final static BsIcon logIn = new BsIcon("log-in", "\\e161");
    public final static BsIcon flash = new BsIcon("flash", "\\e162");
    public final static BsIcon logOut = new BsIcon("log-out", "\\e163");
    public final static BsIcon newWindow = new BsIcon("new-window", "\\e164");
    public final static BsIcon record = new BsIcon("record", "\\e165");
    public final static BsIcon save = new BsIcon("save", "\\e166");
    public final static BsIcon open = new BsIcon("open", "\\e167");
    public final static BsIcon saved = new BsIcon("saved", "\\e168");
    public final static BsIcon import_ = new BsIcon("import", "\\e169");
    public final static BsIcon export = new BsIcon("export", "\\e170");
    public final static BsIcon send = new BsIcon("send", "\\e171");
    public final static BsIcon floppyDisk = new BsIcon("floppy-disk", "\\e172");
    public final static BsIcon floppySaved = new BsIcon("floppy-saved", "\\e173");
    public final static BsIcon floppyRemove = new BsIcon("floppy-remove", "\\e174");
    public final static BsIcon floppySave = new BsIcon("floppy-save", "\\e175");
    public final static BsIcon floppyOpen = new BsIcon("floppy-open", "\\e176");
    public final static BsIcon creditCard = new BsIcon("credit-card", "\\e177");
    public final static BsIcon transfer = new BsIcon("transfer", "\\e178");
    public final static BsIcon cutlery = new BsIcon("cutlery", "\\e179");
    public final static BsIcon header = new BsIcon("header", "\\e180");
    public final static BsIcon compressed = new BsIcon("compressed", "\\e181");
    public final static BsIcon earphone = new BsIcon("earphone", "\\e182");
    public final static BsIcon phoneAlt = new BsIcon("phone-alt", "\\e183");
    public final static BsIcon tower = new BsIcon("tower", "\\e184");
    public final static BsIcon stats = new BsIcon("stats", "\\e185");
    public final static BsIcon sdVideo = new BsIcon("sd-video", "\\e186");
    public final static BsIcon hdVideo = new BsIcon("hd-video", "\\e187");
    public final static BsIcon subtitles = new BsIcon("subtitles", "\\e188");
    public final static BsIcon soundStereo = new BsIcon("sound-stereo", "\\e189");
    public final static BsIcon soundDolby = new BsIcon("sound-dolby", "\\e190");
    public final static BsIcon sound51 = new BsIcon("sound-5-1", "\\e191");
    public final static BsIcon sound61 = new BsIcon("sound-6-1", "\\e192");
    public final static BsIcon sound71 = new BsIcon("sound-7-1", "\\e193");
    public final static BsIcon copyrightMark = new BsIcon("copyright-mark", "\\e194");
    public final static BsIcon registrationMark = new BsIcon("registration-mark", "\\e195");
    public final static BsIcon cloudDownload = new BsIcon("cloud-download", "\\e197");
    public final static BsIcon cloudUpload = new BsIcon("cloud-upload", "\\e198");
    public final static BsIcon treeConifer = new BsIcon("tree-conifer", "\\e199");
    public final static BsIcon treeDeciduous = new BsIcon("tree-deciduous", "\\e200");
    public final static BsIcon cd = new BsIcon("cd", "\\e201");
    public final static BsIcon saveFile = new BsIcon("save-file", "\\e202");
    public final static BsIcon openFile = new BsIcon("open-file", "\\e203");
    public final static BsIcon levelUp = new BsIcon("level-up", "\\e204");
    public final static BsIcon copy = new BsIcon("copy", "\\e205");
    public final static BsIcon paste = new BsIcon("paste", "\\e206");
    public final static BsIcon alert = new BsIcon("alert", "\\e209");
    public final static BsIcon equalizer = new BsIcon("equalizer", "\\e210");
    public final static BsIcon king = new BsIcon("king", "\\e211");
    public final static BsIcon queen = new BsIcon("queen", "\\e212");
    public final static BsIcon pawn = new BsIcon("pawn", "\\e213");
    public final static BsIcon bishop = new BsIcon("bishop", "\\e214");
    public final static BsIcon knight = new BsIcon("knight", "\\e215");
    public final static BsIcon babyFormula = new BsIcon("baby-formula", "\\e216");
    public final static BsIcon tent = new BsIcon("tent", "\\26fa");
    public final static BsIcon blackboard = new BsIcon("blackboard", "\\e218");
    public final static BsIcon bed = new BsIcon("bed", "\\e219");
    public final static BsIcon apple = new BsIcon("apple", "\\f8ff");
    public final static BsIcon erase = new BsIcon("erase", "\\e221");
    public final static BsIcon hourglass = new BsIcon("hourglass", "\\231b");
    public final static BsIcon lamp = new BsIcon("lamp", "\\e223");
    public final static BsIcon duplicate = new BsIcon("duplicate", "\\e224");
    public final static BsIcon piggyBank = new BsIcon("piggy-bank", "\\e225");
    public final static BsIcon scissors = new BsIcon("scissors", "\\e226");
    public final static BsIcon bitcoin = new BsIcon("bitcoin", "\\e227");
    public final static BsIcon btc = new BsIcon("btc", "\\e227");
    public final static BsIcon xbt = new BsIcon("xbt", "\\e227");
    public final static BsIcon yen = new BsIcon("yen", "\\00a5");
    public final static BsIcon jpy = new BsIcon("jpy", "\\00a5");
    public final static BsIcon ruble = new BsIcon("ruble", "\\20bd");
    public final static BsIcon rub = new BsIcon("rub", "\\20bd");
    public final static BsIcon scale = new BsIcon("scale", "\\e230");
    public final static BsIcon iceLolly = new BsIcon("ice-lolly", "\\e231");
    public final static BsIcon iceLollyTasted = new BsIcon("ice-lolly-tasted", "\\e232");
    public final static BsIcon education = new BsIcon("education", "\\e233");
    public final static BsIcon optionHorizontal = new BsIcon("option-horizontal", "\\e234");
    public final static BsIcon optionVertical = new BsIcon("option-vertical", "\\e235");
    public final static BsIcon menuHamburger = new BsIcon("menu-hamburger", "\\e236");
    public final static BsIcon modalWindow = new BsIcon("modal-window", "\\e237");
    public final static BsIcon oil = new BsIcon("oil", "\\e238");
    public final static BsIcon grain = new BsIcon("grain", "\\e239");
    public final static BsIcon sunglasses = new BsIcon("sunglasses", "\\e240");
    public final static BsIcon textSize = new BsIcon("text-size", "\\e241");
    public final static BsIcon textColor = new BsIcon("text-color", "\\e242");
    public final static BsIcon textBackground = new BsIcon("text-background", "\\e243");
    public final static BsIcon objectAlignTop = new BsIcon("object-align-top", "\\e244");
    public final static BsIcon objectAlignBottom = new BsIcon("object-align-bottom", "\\e245");
    public final static BsIcon objectAlignHorizontal = new BsIcon("object-align-horizontal", "\\e246");
    public final static BsIcon objectAlignLeft = new BsIcon("object-align-left", "\\e247");
    public final static BsIcon objectAlignVertical = new BsIcon("object-align-vertical", "\\e248");
    public final static BsIcon objectAlignRight = new BsIcon("object-align-right", "\\e249");
    public final static BsIcon triangleRight = new BsIcon("triangle-right", "\\e250");
    public final static BsIcon triangleLeft = new BsIcon("triangle-left", "\\e251");
    public final static BsIcon triangleBottom = new BsIcon("triangle-bottom", "\\e252");
    public final static BsIcon triangleTop = new BsIcon("triangle-top", "\\e253");
    public final static BsIcon console = new BsIcon("console", "\\e254");
    public final static BsIcon superscript = new BsIcon("superscript", "\\e255");
    public final static BsIcon subscript = new BsIcon("subscript", "\\e256");
    public final static BsIcon menuLeft = new BsIcon("menu-left", "\\e257");
    public final static BsIcon menuRight = new BsIcon("menu-right", "\\e258");
    public final static BsIcon menuDown = new BsIcon("menu-down", "\\e259");
    public final static BsIcon menuUp = new BsIcon("menu-up", "\\e260");

    public final String selector;
    public final String charNumber;

    private BsIcon(String selector, String charNumber) {
        super(null);
        this.selector = selector;
        this.charNumber = charNumber;
    }

    @Override
    public Visual createTag(Parent parent) {
        Span tag = new Span(parent);
        setTag(tag);
        return tag;
    }

    @Override
    public void setTag(Visual tag) {
        Head head = ((Element) tag).getHTML().head;
        head.link(Res.bootstrap);
        tag.cls("glyphicon glyphicon-" + selector);
    }

}
